### ISSUE TITLE
multiple Auth Middleware

### ISSUE THREAD

**Issue by xembill** [highideas/laravel-users-online#51]
Hi is it possible use multiple Auth? 
ex : 
```
 if (Auth::user()) {
            Auth::user()->setCache(config('session.lifetime'));
        }

        if (Auth::guard('otherauth')->user()) {
            Auth::guard('otherauth')->user()->setCache(config('session.lifetime'));
        }
```
if ı change UsersOnline middleware to this, it work well but if auth->user and otherauth->user ids is same that can be problem...

**Comment by GabrielDeveloper** [comment]
@xembill It's possible, you need to change the creation of cache key, which currently uses the user ID instead of an id for each auth.

Another issue is if there are more than 2 auth in your case above, you will use some "if" for each authentication, so its better something more abstract.

We can think on an implementation for this case in next releases, feel free to send PRs.

**Comment by xembill** [comment]
Fix my problem like your comment. Thanks again.
